version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
      args:
        - APP_HOME=/var/app
    command: npm start
    environment:
      MONGODB_ADDRESS: db
    ports:
      - 80:3000
    volumes:
      - .:/var/app
      - /var/app/node_modules
    links:
      - db
    depends_on:
      - db

  mongoexpress:
    image: mongo-express:0.38
    ports:
      - 8081:8081
    links:
      - db:mongo
    depends_on:
      - db

  db:
    image: mongo:3.0
    ports:
      - 27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
